### PR TITLE
[FIX] pos_round_cash_payment: Round the remainder

### PR DESCRIPTION
**Pull request by carmenbianca**
Co-Authored-By: Virginie Dewulf
Signed-off-by: Carmen Bianca Bakker <carmen@coopiteasy.be>

## Odoo task (if applicable)

https://gestion.coopiteasy.be/web#id=8643&action=475&active_id=267&model=project.task&view_type=form&menu_id=536

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

### CODE REVIEW

**Comment by carmenbianca** [comment]
Actually I don't think this fix is correct, even though it appears to work.

On line 32, there's this:

```js
if (remainder !== 0) {
```

I think that needs to become something akin to `if remainder is almost zero`, kind of like Python's [unittest.assertAlmostEqual](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertAlmostEqual).

**Review by robinkeunen — APPROVED** [review]
👍

**Comment by robinkeunen** [comment]
@carmenbianca I think your fix is better though, I prefer having precisely rounded values sent back to the Odoo backend and therefore testing _almostEqual_ is not needed.

**Pull request merged**
